export const SOURCE_TYPES = {
  SAP: "SAP",
  UTILITY: "UTILITY",
  TRAVEL: "TRAVEL",
};

export const RAW_STATUS = {
  PENDING: "PENDING",
  NORMALIZED: "NORMALIZED",
  FAILED: "FAILED",
};

export const RECORD_STATUS = {
  PENDING: "PENDING",
  APPROVED: "APPROVED",
  REJECTED: "REJECTED",
  LOCKED: "LOCKED",
};

export const DATA_SOURCE_STATUS = {
  RECEIVED: "RECEIVED",
  PROCESSED: "PROCESSED",
  FAILED: "FAILED",
};

